const users = require('./users/users.service.js');
const roles = require('./roles/roles.service.js');
const positions = require('./positions/positions.service.js');
const levels = require('./levels/levels.service.js');
const skils = require('./skils/skils.service.js');
const currencys = require('./currencys/currencys.service.js');
const sources = require('./sources/sources.service.js');
const locations = require('./locations/locations.service.js');
const statuses = require('./statuses/statuses.service.js');
const interactionTypes = require('./interaction-types/interaction-types.service.js');
const interactions = require('./interactions/interactions.service.js');
const candidates = require('./candidates/candidates.service.js');
const candidatesPublicProfiles = require('./candidates-public-profiles/candidates-public-profiles.service.js');
const candidatesSkills = require('./candidates-skills/candidates-skills.service.js');
const candidatesUsers = require('./candidates-users/candidates-users.service.js');
// eslint-disable-next-line no-unused-vars
module.exports = function (app) {
  app.configure(users);
  app.configure(roles);
  app.configure(positions);
  app.configure(levels);
  app.configure(skils);
  app.configure(currencys);
  app.configure(sources);
  app.configure(locations);
  app.configure(statuses);
  app.configure(interactionTypes);
  app.configure(interactions);
  app.configure(candidates);
  app.configure(candidatesPublicProfiles);
  app.configure(candidatesSkills);
  app.configure(candidatesUsers);
};
